### ISSUE TITLE
Synapse Serverless not supported with .sqlproj

### ISSUE THREAD

**Issue by jds3d** [microsoft/DacFx#262]
- SqlPackage or DacFx Version: 16.1.8089.0
- .NET Framework (Windows-only) or .NET Core:  7.0.203
- Environment (local platform and source/target platforms): Powershell version 7.3.4 on Windows 11.

**Steps to Reproduce:**

1. Open powershell
2. Execute 'dotnet new install Microsoft.Build.Sql.Templates'
3. Execute 'dotnet new sqlproj -n "Test" -tp SqlServerless'

Output is:
Error: Invalid option(s):
-tp SqlServerless
   'SqlServerless' is not a valid value for -tp. The possible values are:
      Sql130        - SQL Server 2016
      Sql140        - SQL Server 2017
      Sql150        - SQL Server 2019
      Sql160        - SQL Server 2022/Azure SQL MI
      SqlAzureV12   - Azure SQL Database
      SqlDw         - Azure Synapse SQL

4. If i select another one or don't specify the target platform and then try to build the project, I get this:
 C:\Users\[user]\source\repos\test\External Resources\Environments\development\external_file_format.sql(1,1,1,1): Build error SQL70015: Statement 'CREATE EXTERNAL FILE FORMAT' is not supported for the targeted platform. [C:\Users\[user]\source\repos\test\test.sqlproj]

external_file_format.sql contains this:
CREATE EXTERNAL FILE FORMAT DeltaFormat
WITH 
(
    FORMAT_TYPE = DELTA
);
GO

That code runs just fine in Synapse Serverless directly.

Note: The only way I was able to determine that -tp SqlServerless might be the right choice is from looking at the source code in this project:
https://github.com/microsoft/DacFx/blob/3760d5c152c67b78845f20c165aa0614f3568616/src/Microsoft.Build.Sql.Templates/sqlproject/.template.config/template.json

**Did this occur in prior versions?  If not - which version(s) did it work in?**
As Synapse Serverless is a new feature, I don't think this would have worked in an old version either.
(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by jds3d** [comment]
Hi @zijchen have you been able to reproduce this error?

**Comment by zijchen** [comment]
@jds3d I am able to reproduce the error with 0.1.9-preview but this has been fixed in #243. The `-tp SqlServerless` will be supported in the next release (ETA later this week).

**Comment by jds3d** [comment]
I @zijchen, @llali, I have to request this be reopened as I'm still seeing part of the error.  -tp SqlServerless works, and creates a project with 
 <DSP>Microsoft.Data.Tools.Schema.Sql.SqlServerlessDatabaseSchemaProvider</DSP>

However, I'm still unable to create an external file format.  
 Build error SQL70015: Statement 'CREATE EXTERNAL FILE FORMAT' is not supported for the targeted platform.

**Comment by zijchen** [comment]
@jds3d I can reproduce that actually. Do you mind creating a new issue for this? Meanwhile I'll look into the missing support for that statement on Synapse Serverless.
